substitutions:
  name: "microgreens"

esphome:
  name: $name
  includes: "HX711I2c.h"
  friendly_name: $name
  name_add_mac_suffix: true
  project:
    name: esphome.microgreens
    version: "1.0"

esp8266:
  board: d1_mini

api:
  reboot_timeout: 0s

ota:

improv_serial:

wifi:
  ap:
    ssid: "ESP Microgreens"

captive_portal:

dashboard_import:
  package_import_url: github://majklovec/esphome-nodes/microgreens-esp8266.yaml

web_server:
  port: 80

logger:
  level: DEBUG

i2c:
  sda: GPIO15
  scl: GPIO14
  scan: true

prometheus:

ads1115:
  - address: 0x48

pca9554:
  - id: "pca9554a_device"
    address: 0x41

text_sensor:
  - platform: template
    id: time_txt
    name: "Actual time"

  - platform: template
    id: light_range
    name: "Light range"

number:
  - platform: template
    id: start_hr
    name: start_hr
    min_value: 0
    max_value: 23
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - script.execute: update_duration

  - platform: template
    id: start_mn
    name: start_mn
    min_value: 0
    max_value: 59
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - script.execute: update_duration

  - platform: template
    id: stop_hr
    name: stop_hr
    min_value: 0
    max_value: 23
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - script.execute: update_duration
  - platform: template
    id: stop_mn
    name: stop_mn
    min_value: 0
    max_value: 59
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - script.execute: update_duration

  - platform: template
    name: "Watering interval (mins)"
    id: interval_watering
    min_value: 0
    max_value: 480
    step: 5
    optimistic: true
    restore_value: true
  - platform: template
    name: "Watering duration (secs)"
    id: duration_watering
    min_value: 0
    max_value: 120
    step: 1
    optimistic: true
    restore_value: true

  - platform: template
    name: "Fan interval (mins)"
    id: interval_fan
    min_value: 0
    max_value: 120
    step: 5
    optimistic: true
    restore_value: true
  - platform: template
    name: "Fan duration (secs)"
    id: duration_fan
    min_value: 0
    max_value: 120
    step: 1
    optimistic: true
    restore_value: true

binary_sensor:
  - platform: template
    id: lights_automation
    lambda: |-
      int start = id(start_hr).state * 60 + id(start_mn).state;
      int stop = id(stop_hr).state * 60 + id(stop_mn).state;
      int now = id(sntp_time).now().hour * 60 + id(sntp_time).now().minute;

      if (start + stop == 0) {
        return false;
      } 

      if (start < stop) {
        if (now >= start && now < stop) {
          return true;
        }
      } else {
        if (now >= stop && now < start) {
          return true;
        }
      }
      return false;
    on_press:
      then:
        - light.turn_on: lights
    on_release:
      then:
        - light.turn_off: lights

  - platform: template
    id: water_automation
    lambda: |-
      int interval = id(interval_watering).state;
      int now = id(sntp_time).now().hour * 60 + id(sntp_time).now().minute;
      int seconds = id(sntp_time).now().second;

      if (interval != 0 && now % interval == 0 && seconds == 0) {
        return true;
      } 
      return false;
    on_press:
      then:
        if:
          condition:
            not:
              script.is_running: watering
          then:
            - script.execute: watering

  - platform: template
    id: fan_automation
    lambda: |-
      int interval = id(interval_fan).state;
      int now = id(sntp_time).now().hour * 60 + id(sntp_time).now().minute;
      int seconds = id(sntp_time).now().second;

      if (interval != 0 && now % interval == 0 && seconds == 0) {
        return true;
      } 
      return false;
    on_press:
      then:
        if:
          condition:
            not:
              script.is_running: fanning
          then:
            - script.execute: fanning

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 3

  - platform: bme680
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
    gas_resistance:
      name: "Gas Resistance"
    address: 0x77
    update_interval: 30s

  - platform: tsl2561
    name: "Ambient Light"
    address: 0x49
    update_interval: 30s

  - platform: vl53l0x
    name: "Water level"
    address: 0x29
    update_interval: 1min
    accuracy_decimals: 2
    unit_of_measurement: "%"
    filters:
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 3
      - sliding_window_moving_average:
          window_size: 15
      - calibrate_linear:
          - 0.028 -> 100
          - 1 -> 0

  - platform: ads1115
    multiplexer: "A2_GND"
    update_interval: 1min
    gain: 4.096
    name: "EC"
    id: ec
    unit_of_measurement: "S"
    filters:
      - lambda: if(id(water).state) { return {}; } else { return x; }
      - quantile:
          window_size: 7
          send_every: 4
          send_first_at: 3
          quantile: .9
      - lambda: return (133.42*x*x*x - 255.86*x*x + 857.39*x);

  - platform: ads1115
    multiplexer: "A3_GND"
    update_interval: 1min
    gain: 4.096
    name: "pH"
    unit_of_measurement: ""
    accuracy_decimals: 1
    id: ph
    filters:
      - lambda: if(id(water).state) { return {}; } else { return x; }
      - quantile:
          window_size: 7
          send_every: 4
          send_first_at: 3
          quantile: .9
      - calibrate_linear:
          - 0 -> 0
          - 5 -> 14

  # - platform: ntc
  #   sensor: resistance_sensor
  #   calibration:
  #     b_constant: 3550
  #     reference_temperature: 25°C
  #     reference_resistance: 10kOhm
  #   name: NTC Temperature
  # filters:
  #    -  offset:  +2.5

  # - platform: resistance
  #   id: resistance_sensor
  #   sensor: ads1
  #   configuration: DOWNSTREAM
  #   resistor: 10.0kOhm

  # - platform: ads1115
  #   multiplexer: 'A0_GND'
  #   gain: 2.048
  #   id: ads1

  - platform: custom
    lambda: |-
      auto my_sensor = new HX711I2c();
      App.register_component(my_sensor);
      return {my_sensor->cell[0], my_sensor->cell[1], my_sensor->cell[2]};
    sensors:
      - name: "cell1"
        id: "cell1"
        accuracy_decimals: 0
      - name: "cell2"
        id: "cell2"
        accuracy_decimals: 0
      - name: "cell3"
        id: "cell3"
        accuracy_decimals: 0

switch:
  - platform: restart
    name: "Restart"

  - platform: gpio
    name: "02. Water"
    id: water
    pin:
      pca9554: pca9554a_device
      number: 0
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "03. Fans"
    id: fan
    pin:
      pca9554: pca9554a_device
      number: 1
      mode:
        output: true
      inverted: false

output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 1000 Hz
    id: pwm_output

light:
  - platform: monochromatic
    output: pwm_output
    name: "01. Lights"
    id: lights
    default_transition_length: 3s

button:
  - platform: template
    name: "Watering"
    icon: "mdi:watering-can"
    id: watering_button
    on_press:
      then:
        - script.execute: watering
script:
  - id: watering
    then:
      - switch.turn_on: water
      - delay: !lambda return id(duration_watering).state * 1000;
      - switch.turn_off: water

  - id: fanning
    then:
      - switch.turn_on: fan
      - delay: !lambda return id(duration_fan).state * 1000;
      - switch.turn_off: fan

  - id: update_duration
    then:
      - lambda: |-
          char str[35];
          int sh = id(start_hr).state;
          int sm = id(start_mn).state;
          int eh = id(stop_hr).state;
          int em = id(stop_mn).state;

          int start = sh * 60 + sm;
          int stop = eh * 60 + em;


          if (start < stop) {                  
            float dh = (stop - start) / 60.0;
            sprintf(str, "%u:%u -> %u:%u (%.1f h)", sh, sm, eh, em, dh);
          } else {
            float dh = (start - stop) / 60.0;
            sprintf(str, "%u:%u -> %u:%u (%.1f h)", eh, em, sh, sm, dh);
          }

          id(light_range).publish_state(str);

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Prague

status_led:
  pin:
    number: GPIO2
    inverted: true
