name: Build and Publish ESPHome firmware and website

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.yaml"
      - "static/**"

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  build-presence:
    name: Publish Presence
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: presence-esp32c3.yaml
      name: Presence sensor
      manifest_filename: presence.json
      clean: false
      esphome_version: latest
  build-bedweight:
    name: Publish Bedweight
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: bedweight-esp32.yaml
      name: Bed sensor
      manifest_filename: presence.json
      clean: false
      esphome_version: latest
  build-microgreens:
    name: Publish Microgreens
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: microgreens-esp32.yaml,microgreens-esp8266.yaml
      name: Microgreens
      manifest_filename: microgreens.json
      clean: false
      esphome_version: latest
  build-lightemp:
    name: Publish Lightemp
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: lightemp-esp32.yaml
      name: Light, humidity, temperature sensor
      manifest_filename: presence.json
      clean: false
      esphome_version: latest
  build-table:
    name: Publish table
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: table-logicdata-esp8266.yaml
      name: Standing table
      manifest_filename: presence.json
      clean: false
      esphome_version: latest
  build-sonoff:
    name: Publish sonoff
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: sonoff-basic-r1.yaml
      name: Sonoff basic
      manifest_filename: presence.json
      clean: false
      esphome_version: latest
  # Deploy job
  deploy:
    # Add a dependency to the build job
    if: ${{ always() }}
    needs:
      [
        build-presence,
        build-bedweight,
        build-lightemp,
        build-microgreens,
        build-sonoff,
        build-table,
      ]
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
